### ISSUE TITLE
Windowless Mode (New Feature)

### ISSUE THREAD

**Issue by ecokeley** [benkeen/generatedata#128]
It would be very useful to be able to run my Profile Data Sets from scripts!  I'm really liking this application, just wrote an RGB type (needs polishing)!  I'm thinking of using this to generate Integration Testing data at my company.
-Erik

**Comment by benkeen** [comment]
This is now, finally, on the books for v4! :) After documenting v4, converting this app to run as an npm package is my main focus. 

But I'll close this now - going through old tickets and closing off the old ones. Thanks @ecokeley!
