### ISSUE TITLE
Add apostrophes in names

### ISSUE THREAD

**Issue by davidwebca** [benkeen/generatedata#134]
There should be an option somewhere to be able to export "dangerous" data.

What I mean is that I often use generatedagta to try to insert an array of new data through a form or to pass through my php validation, but the most needed kind of data would be something like the name "O'Brien" or with similar special characters. They often break mysql inserts and they are a soft test against mysql injection.

**Comment by benkeen** [comment]
Bit of a paltry solution but I added in a few names with apostrophes. Agreed, some way to mess up the data would be ideal but that's a lot of work and I have nothing planned for that.
