### ISSUE TITLE
Tamil Translation has lot of errors

### ISSUE THREAD

**Issue by fareez-ahamed** [benkeen/generatedata#196]
Hi Ben,

I was reviewing Tamil translation, and it seems to have lots of errors and looks converted using Google Translate. Please set it to disabled... I'm working on it, I will give a pull request when done.

Fareez

**Comment by benkeen** [comment]
v4 has the Tamil translation added now, but it may well contain many errors. Closing this old ticket now but do feel free to contribute better translations!
