### ISSUE TITLE
Company Name option can contain ";"

### ISSUE THREAD

**Issue by tumbo** [benkeen/generatedata#210]
The option to generate a random company name appears to use content in the table gd_settings.  One of the records contains the default SQL termination character ";".  

../resources/classes/Installation.class.php loads a large text field into the gd_settings table which contains a ";".  Look for "Curae;".

I'm guessing this is a typo and it was intended to be the letter "l".  When generating to SQL, this creates a problem where the statement terminates prematurely and an error is thrown.

**Comment by fontaju** [comment]
found this bug again today . "Curae;"  appears sometimes . I suppose it shall be "Curae."
