### ISSUE TITLE
Installation in a loop after "Compete"

### ISSUE THREAD

**Issue by frankvg** [benkeen/generatedata#249]
Install worked fine on a Windows Server. Great product! 

On the Linux server, the install gets to step 5, "Complete", and then you click on "Go to script" and it returns to Step 3 of the installation.  I've gone through it multiple times with no change. Using download from today. Checked the server logs and the strange error appears (with items in brackets removed):

Permission denied: [root]/datagen/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable, referer: http://[Site]/datagen/install.php

There is no .htaccess file there. The entire datagen directory has the permission 777 (yes, that's awful, but it fails to start with anything less).

Is the installer supposed to install this file or should I create the file myself?  Any idea what should be in it? Oddly the only file that references htaccess it is under:  resources\libs\codemirror\mode\nginx\index.html

Lastly, once installed, can you downgrade the permissions instead of 777? Seems like a significant security hole to require 777 permissions to work. For us at least this is a non-production server with little of value.

**Comment by Amerisun** [comment]
I had the same problem just now, in case anyone else has it seems that the settings.php file even if you create it and make it writeable to anyone the application never actually enters the data if you get past that point.   Go edit the settings.php file and put the database details in there, making sure not to have an _ for your table prefix and it will continue and work after that.

**Comment by benkeen** [comment]
Thanks for the info, everyone! Man, I'm having a devil of a time reproducing this problem - but obviously there's a hole here somewhere. I'll keep tinkering.

**Comment by benkeen** [comment]
k, I'm damned if I can see a problem. I've read some cases of `fopen` and `fwrite` creating blank files - but no solutions. What I've done is added an check after creating the file to confirm it contains everything you'd expect. If it doesn't, it'll notify you in the interface - or best case scenario (if you don't have permissions) actually generate the `settings.php` content and display it in the UI for you to create manually. 

Oh and @Amerisun is quite right - manually creating the file is always a simple workaround (but please let me know if this occurs to you). Just base the contents on the `settings.example.php` file in the root folder.

**Comment by mentalzombi** [comment]
Bit late on this thread, but for info I saw this issue after a successful install on a Redhat 6 server.  It experienced an uncontrolled powered off.  On startup mysql didn't start due to an existing mysql.sock file being in place.  This caused the issue described above.  In my instance moving the mysql.sock to the side and starting the service resolved the problem.
