### ISSUE TITLE
Batch insert not working in Oracle

### ISSUE THREAD

**Issue by kaaku** [benkeen/generatedata#252]
When using the "INSERT batch size" option and having Oracle as the database type, the generated SQL has an invalid syntax. The generated SQL looks like this:

INSERT INTO table (foo,bar) VALUES ('foo1','bar1'),('foo2','bar2');

Executing this gives the following error:

SQL Error: ORA-00933: SQL command not properly ended

The SQL should instead look like this:

INSERT ALL
    INTO table (foo, bar) VALUES ('foo1', 'bar1')
    INTO table (foo, bar) VALUES ('foo2', 'bar2')
SELECT * FROM dual;

I'm running version 3.1.4 of generatedata and both Oracle 10 and 11.

**Comment by benkeen** [comment]
Hmmm... I didn't close this. Attaching to 3.2.1 - I'll confirm it's fixed or fix it there.

**Comment by benkeen** [comment]
Seems like the batch option doesn't really add anything for Oracle - the end result is still pretty verbose, so I'm just going to remove the option for Oracle.
