### ISSUE TITLE
Some Issue!

### ISSUE THREAD

**Issue by charles111** [benkeen/generatedata#258]
![2014-11-10 1 40 06](https://cloud.githubusercontent.com/assets/8487403/4971246/45c8120c-68df-11e4-88b0-022084c2c379.png)

i am having this error message 
i can't use it in my local PC 
plz help

**Comment by benkeen** [comment]
Hi - sorry I never responded to this. In case anyone else runs into it, it's just due to invalid database credentials. Possibly the database doesn't exist or the MySQL username/password is incorrect.
