### ISSUE TITLE
Docker container for easy setup for of a php-server

### ISSUE THREAD

**Issue by nate9** [benkeen/generatedata#259]
Hi all,

I've set up a docker container for generatedata. It allows for easy setup of a php-server in a self contained service.

You can pull the image by using 
> docker pull lai475nathaniel/docker-generatedata

or by cloning my repo here: https://github.com/LaiNathaniel/docker-generatedata and building it yourself using docker.

Alternatively, if you have fig and docker installed, you can just clone the git repository, and use
> fig up

and it will create both a php server with generate data and a mysql server. In the setup, the mysql server's hostname will automatically be configured to be "mysql" for the php server.

Hope this helps

**Comment by benkeen** [comment]
Main README links to this. Closing.
