### ISSUE TITLE
can't save

### ISSUE THREAD

**Issue by kveale** [benkeen/generatedata#264]
i am using chrome browser. i was able to save one data set. After that, when i attempt to save a new data set, the busy indicator spins continuously and the data set is never saved.

**Comment by geoffh999** [comment]
I am using Chrome as well and am an Online user BUTmaybe the site is just timing out too quick because sometimes I can't save either - progress spinner just keeps spinning.  If a Login time-out, message should tell user.  Thanks!

**Comment by benkeen** [comment]
Hey @geoffh999 - try logging out then in again - or even closing your browser and restarting. It's possible there's a bug after initially signing up. The other couple of cases I've heard of that happening was specifically after first logging in.

**Comment by geoffh999** [comment]
Thanks - that seemed to work.  I've been able to generate the data I needed
for now.  Nice tool that saves a bunch of Excel or SQL scripting time !

On Wed, Apr 8, 2015 at 2:15 PM, Benjamin Keen <notifications@github.com>
wrote:

> Hey @geoffh999 <https://github.com/geoffh999> - try logging out then in
> again - or even closing your browser and restarting. It's possible there's
> a bug after initially signing up. The other couple of cases I've heard of
> that happening was specifically after first logging in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benkeen/generatedata/issues/264#issuecomment-91008399>
> .
>



-- 
Geoff Humphreys
