### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by rpoelking** [benkeen/generatedata#268]
After running the installation script, it always loops back step 3 user accounts. I'll click Continue, Run through the install plugins and I get "success" for all plugins. Then click continue, click  "go to script" and I end right back at step 3 again.

**Comment by vsmurali** [comment]
This happens in linux / mac when the directory does not have write permissions. chmod 777 to the directory and installation should go through fine

**Comment by nesttle** [comment]
Same here, Windows 7 64Bits and XAMPP :(

**Comment by benkeen** [comment]
Seems like this is a common problem, I'm going to look at it for the next release.

**Comment by benkeen** [comment]
Duplicate of #249

**Comment by rpoelking** [comment]
OK, Installed and after a few "Oops" hiccups got through the script and got the exact same thing at the end when I click "'run script." I end right back at the set up users screen. Then realized I forgot to chmod the folder...that didn't help. Start all over from scratch...removed the schema, recreated the schema, new folder, chmodded it added new files and THEN it ran.
