### ISSUE TITLE
Inappropriate language (possibly?) in results

### ISSUE THREAD

**Issue by dpkonofa** [benkeen/generatedata#271]
I'm not sure how the data used is actually generated or from where, but we've generated a bit of data with this and some of the street names and content are probably inappropriate.  We've gotten things like "Cum Ave", "Vestibulum Road", and "Molester Dr." as results in the list.  Is there a filter or anything for that?

**Comment by benkeen** [comment]
haha :) It's just Latin, pulled from lorem ipsum. Since it's just used randomly I don't mind removing those words if you like. Let me know of any others that could be misinterpreted & I'll remove them.
