### ISSUE TITLE
Generates 100 entries no matter what

### ISSUE THREAD

**Issue by kika** [benkeen/generatedata#273]
I've created an account and donated, now the website allows me to change the Rows field, bit it still generates just 100 entries no matter what.

**Comment by benkeen** [comment]
Hi @kika, try logging out and then in again. It's possible that the old info was cached and it doesn't all you to edit that field. Let me know if that fixes it.  

[And thanks for the donation!].

**Comment by kika** [comment]
Yep, that worked today. Didn't work yesterday though, so probably cache has very long TTL. BTW, I didn't create an account before donating, so my account was "donated" from the get go. Nevertheless, it works now and I've generated 1000 rows.
