### ISSUE TITLE
Page not found error 403 when trying to login after successful installation

### ISSUE THREAD

**Issue by amit1683** [benkeen/generatedata#277]
I am getting error : Page not found 403, when trying to login after successful installation (v3.1.4).
Login page opens up fine and accepts id and pass but on pressing continue button it gives this error.
I have hosted code on "www.amitkumar11.dx.am".

**Comment by benkeen** [comment]
This very much sounds like a server error, I'm afraid. Hope you managed to get somewhere with it. :(
