### ISSUE TITLE
issue with charset

### ISSUE THREAD

**Issue by tintinux** [benkeen/generatedata#279]
Wonderful job !

I have installed the scripts in my server, It was easy and everything works very well, except an issue.

When I save a dataset with accentuated characters in its name, and display the list of saved dataset, characters are not coded correctly... It looks like a double encoding...  

![generatedata](https://cloud.githubusercontent.com/assets/5647690/7087237/692d49d0-df89-11e4-9e74-e7f2b687bfa4.png)

Note : Before installation, I created the database as required. It was with UTF-8 charset by default, but I didn't found any hint about this.

Best regards

**Comment by benkeen** [comment]
Ooh, thanks @tintinux. I have a bunch of PRs and bugs for this script I need to look at - I'll try to get to it soon.
