### ISSUE TITLE
File format lost

### ISSUE THREAD

**Issue by bludv** [benkeen/generatedata#282]
We have just donated to this application to get an account.  We have a 387 column file that we need to produce.  We spent all day typing in the data set specifications, saving many times on the 6th May 2015.  The file fomat says it was last saved at 4:40pm.  But when we opened the file format today there is only 49 columns and the columns are no longer in the order we entered them.  After this corruption of the file, it seems we have lost a full day's work because there doesn't seem to be any way of inserting columns except at the end of the file, which means there is no way to recover but start again from scartch.  With 387 columns this is going to take another 3 days. We are concerned we will be wasting our time.  Can you please advise 1) is there a column restriction / limit (there is nothing we can see on the web site that highlights these limits; 2) is there anyway we can import the field names from a csv file so we don't have to spend days typing them in manually; 3) is there any way to insert columns in between two existing columns or do you have to delete all the columns back to the mistake you made and then re-enter them all again; 4) could we save the file format partially complete - as it takes so long to enter it would be nice to be able to upload all the field names then regularly save the parameters as we get to them, but save is prevented until everything has been filled in at the moment.

**Comment by benkeen** [comment]
Hi @bludv - I'm so sorry you ran into trouble, I can only imagine how frustrating this is. :(

1. So first off, there's no limitation in the code - JS or PHP that limits the number of columns. But with such a giant data set, it's possible you've stumbled into a new problem. You're the first person I've heard of using it with such a huge set, so possibly there's a limitation on the PHP/Apache configuration that limits request sizes, or maybe the request to save was so large it simply timed out... I'll have to do some investigation. See below.

2. No I'm afraid there's no import mechanism for populating the field names from an external source, it all needs to be done through the interface. The only other option is to use the API [see: http://benkeen.github.io/generatedata/api.html]. If you have a developer handy, that may well be a much better solution for you - but it's a lot more work.

3. Yes, you can sort the rows by mousing over the first column that contains the row number it in. Just click and drag the row up or down to change the order.

4. This is a really legit question. I've always encouraged people to save their data sets often, but the truth is after reading your post, it dawned on me that if anything gets corrupted - like the request only half gets through - or anything else - the data can get lost. The best way around this would be to store a list of *all* versions of a document with the option in the UI to retrieve any version. So if one gets lost, you can at least retrieve the latest backed-up version. I'm going to add this as a feature request and try to get it into the next release. But I don't know when I'll have time to work on that.

Let me blunt: I would NOT recommend spending more time re-inputting it. 3-days of inputting data is just far too much work to risk the same thing happening again, and it's very possible that it may do that. 

Can you split your data set into two and generate them in separate chunks? Can the data set be reduced in any other way? If not, I think you may be out of luck. 

Lastly, and I know this is a very poor answer, but of course you're absolutely welcome to a refund. The donation option is really just there so I can continue paying for the hosting (you wouldn't believe how costly its gotten!). Just send me an email at ben.keen@gmail.com.

**Comment by benkeen** [comment]
I'm going to add an auto-backup option to at least mitigate this issue in this ticket: https://github.com/benkeen/generatedata/issues/283

**Comment by bludv** [comment]
I have now had my technical guys try to install your application on a server.  We are up to installation step "3. User Accounts" and we get an "Uh-oh There was a problem creating the core tables. Please report this problem." Note: The database has root access.

**Comment by bludv** [comment]
Also he said it only works with Chrome and we can't use internet explorer!  What's that about?

**Comment by benkeen** [comment]
What version of IE are you using? 

Regarding the installation error, that's a first. Feel free to pass on my email to your tech guy: ben.keen@gmail.com - we'll need to debug that together.

**Comment by bludv** [comment]
My techy said that the version before the last version did not have this bug "3. User Accounts" and we get an "Uh-oh There was a problem creating the core tables. Please report this problem." Note: The database has root access.  So we installed the second to last version and it installed ok.  So looks like you've introduced this defect in the last version only.

**Comment by bludv** [comment]
Is there any way possibility that you could send me my format files from your server because we don't want to have to spend another 4 days setting up the file formats again on our own local server installation.  With the short idol timeout issues on your server, we are keen to migrate to our own server so we don't keep losing our work.

**Comment by benkeen** [comment]
Hi @bludv, it really sounds like this may not be the tool for you at this stage. You've identified some issues which I'm looking into, but I don't want you spending more time on this and continuing to be frustrated when it doesn't match up. 

I can send you the raw content of the database for your account, but that's the only backup of the data that currently exists.

**Comment by benkeen** [comment]
I've added the history backup in 3.2.1 which I'll release shortly. I won't be updating the live site until it's been out in the wild for a while.
