### ISSUE TITLE
All saved file formats gone

### ISSUE THREAD

**Issue by bludv** [benkeen/generatedata#284]
We have just spent all day creating file formats in 50 field blocks, intending to join the results for our 387 input file format back together in Excel since we discovered this application is unable to cope with more than 100 columns.

So my staff member started to create them and I told her to save after every 10 fields. She did several files this way and got up to 40 then it got stuck and the little round refresh icon spun for 25 minutes and nothing. I suggested she save it as a different file name.  The screen was locked and we couldn't do this.  So we refreshed the page. Much to our dismay EVERY data set specification was gone and deleted from our account.  

So after paying you $27AUD we still can't even reliably save our data set specifications and are no better off than using the product without donating to you.  This product seems very unstable and unreliable to me.  You've seem to have done a lot of work on language translations, country address formats etc. but really the basics that users need - like the ability to save a file format - are what desperately needs your attention.

**Comment by benkeen** [comment]
Hi @bludv, I responded to you yesterday here: https://github.com/benkeen/generatedata/issues/282 - mind if we speak there?
