### ISSUE TITLE
install script fails on step 4 between export type and countries

### ISSUE THREAD

**Issue by milburnr** [benkeen/generatedata#292]
![image](https://cloud.githubusercontent.com/assets/13068484/8383924/856f75d4-1bfa-11e5-8336-e187ddae3407.png)

**Comment by milburnr** [comment]
BTW installed on a website hosted on GoDaddy, should be a current version of PHP

**Comment by benkeen** [comment]
Sorry for not getting to this sooner. Seems like others are running into problems on this step too. 

Are you on Chrome / Firefox? Are you comfortable with devtools or firebug? If possible, could you show the me the failed requests that take place during a failed installation? I'm curious to know if it's the same issue spotted by others.

**Comment by benkeen** [comment]
Also - if you or anyone running into an installation problem like this and would like me to debug it directly on the server, just send me an email at ben.keen@gmail.com. I'd like to see it!

**Comment by milburnr** [comment]
Hi Ben - thanks for getting back to me on this! I managed to get it
working... it was a matter of needing the 32 bit version of a C runtime (or
something like that) - if I recall correctly, I had installed the 64bit
version because Windows was 64bit, but I missed that something said to use
the 32 bit one. That might be what is causing things to halt for others
too, if they are missing that detail. It's so ingrained to install 64 bit
on 64 bit OS that it was weird to install the 32 bit version.

Hope that helps somewhat. Otherwise - it was a very useful tool! I used it
to generate 50,000 names to import into my lab Active Directory, ran IdFix
(Office 365 tool) and found about 3000 dupes, removed those, and then
synced them to my test Office 365 tenant. It worked for my needs perfectly.
So thanks!!

Rich

**Comment by benkeen** [comment]
No worries, glad you got it solved! :D

**Comment by dgoodrumjsonar** [comment]
Hi @benkeen ,

I am having a very similar issue, except that it gets stuck between data types and export types. The export types never completes. At first I got an http 500 error, but I changed something and now I just get a forever spinner.

Thanks,
David
