### ISSUE TITLE
api/v1/data folder missing for REST API call

### ISSUE THREAD

**Issue by thilaksatish** [benkeen/generatedata#293]
Hello Benjamin,

Thanks for your tool. I'm excited to use your REST call approach to be able to generate data programmatically. I downloaded the necessary files and followed the steps to enable the apiEnabled variable in the settings.php. Everything went through fine but I don't see the v1/data folder insider api folder. Your example mentions, a POST call to http://{url}/api/v1/data and a JSON body is all needed to get a response. I'm unable to perform a POST without the folder. Could you tell me what I'm missing here?

I tried both 3.2.0 and 3.2.1 versions of generatedata. I'm running a WAMP server with PHP(5.5.12) and MySQL(5.6.17) and Apache(2.4.9).

I appreciate your help.

Thanks,
Thilak

**Comment by luckyincode** [comment]
Yeah, I'd like to know about this as well.

**Comment by benkeen** [comment]
Hey! Actually, there's no `data` folder - it's purely for the API endpoint to identify what requests to examine and parse.

I don't quite follow when you say you can't POST to the folder... try creating a request that does just that (you can create requests that post anywhere, regardless of the place actually existing or not) and let me now what response you get. It's possible there's an issue with the .htaccess configuration that's preventing the requests from getting through to the code, but let's start there.

**Comment by thilaksatish** [comment]
Hey,

You're amazing. .htaccess configuration was missing and I modified it and it works perfectly.

I can get to work now!

Thanks a ton for your quick response.

Thilak

**Comment by benkeen** [comment]
Nice! :) Let me know if you run into any problems with it - I'm curious to see how you find it to work with. Hopefully the error messages will help out when you're constructing your queries.

**Comment by thilaksatish** [comment]
Sure thing! I'll follow up soon.

**Comment by Abdelrahman-Hasan** [comment]
Dear Mr. benkeen
i have the same problem
please help me-->what should be the content of .haccess file ?
thanks
