### ISSUE TITLE
"Add default auto-increment column" checked when reloading data set

### ISSUE THREAD

**Issue by psauvetre** [benkeen/generatedata#295]
I saved a data set with "None" option for primary key.
After reloading the data set the option is not restored properly, instead "Add default auto-increment column" is checked. See attached image.
I installed generatedata via vagrant (generatedata-vagrant).

![generatedata_reload_dataset_issue](https://cloud.githubusercontent.com/assets/13344874/8958355/a9a8beb4-3604-11e5-84f5-90712656a4b1.PNG)

**Comment by benkeen** [comment]
Thanks @psauvetre - I'll check it out!

**Comment by benkeen** [comment]
Yup, this is a bug. I'll fix it in the next release, thanks!

**Comment by psauvetre** [comment]
Thanks!
