### ISSUE TITLE
Generating 100k records with 10 number range columns fails

### ISSUE THREAD

**Issue by shahamit** [benkeen/generatedata#307]
We have deployed 3.2.1 version of generatedata tool locally. It works fine for small set of records but for medium data sets it doesn't seem to be working. 

We tried with 10 number range columns and 100k records as shown in the screenshot [here](http://pasteboard.co/x4NDpJT.png). 

Is there a limit to the number of records this tool can generate or am I missing some configuration?

Thanks!

**Comment by benkeen** [comment]
Hi @shahamit - sorry you're having trouble! No, there's no hardcoded limit, but 100,000 would take a long time so it's probably timing out on you. Still... there's shouldn't be much math involved with your particular data set, so I'm a little surprised it won't run.

You have a couple of options: 
1. create smaller results (10,000 maybe) and see if they last. 
2. Tweak line 34 of /resources/classes/Core.class.php from this:
```private static $timeout = 300; // 5 minutes```

to this:
```private static $timeout = 3000; // 50 minutes```

That should be configurable by not editing that file, apologies. I'll ensure it's in the next tag.

**Comment by shahamit** [comment]
I will try out these options and follow up. I have a couple of comments
1. I missed mentioning it in my original comment that I select the "Prompt to download" option for generating data for 100k rows that opens up a new browser window but that does not show any download popup.
2. Does the software generate any informative/debug/trace level logs that could be further looked upon and shared here for troubleshooting the issue?

Thanks!

**Comment by akarambalkar** [comment]
I am not sure about which file should I edit this $timeout parameter...Is this something in code or some properties file that I should make changes ?
 
Not sure about the file location to make these changes.

Please guide me to the location or file details so that I can make these changes and try

**Comment by tobya** [comment]
@akarambalkar what happens when you don't select the download option, does it fill the other browser windows with the data?

**Comment by benkeen** [comment]
Closing old tickets. v4 handles larger data sets a lot better.

**Comment by benkeen** [comment]
Closing old tickets. v4 handles larger data sets a lot better.

**Comment by benkeen** [comment]
Closing old tickets. v4 handles larger data sets a lot better.
