### ISSUE TITLE
Can't generate > 100 records after 1st generation in same session

### ISSUE THREAD

**Issue by dankasak** [benkeen/generatedata#308]
I've installed locally and logged into the web front-end. I can generate 1,000,000 records for SQL Server and these work fine. After this though, I can only generate 100 records at a time, no matter what I select. Logging out and back in 'solves' this.

**Comment by benkeen** [comment]
Sorry for not getting back to you on this. Sounds like the sessions are being lost, so the system thinks you're no longer logged in. Not sure why though...

To confirm, could you try this?
- log in
- generate > 100 records.
- wait a bit.
- generate > 100 records again. 
- confirm only 100 results are returned. 
- click refresh in your browser.

At this point, if you're no longer logged in, you'll see a "Login" link in the header.

**Comment by benkeen** [comment]
Closing because it's gotten stale. Please re-open if it's still an issue.
