### ISSUE TITLE
Encoding wrong with sqlite generation

### ISSUE THREAD

**Issue by tempelmann** [benkeen/generatedata#309]
When you generate for sqlite and have German city names included (e.g. "Fürth), they come out at "F�rth" in the generated html page (whereas the html header says that it's utf-8 encoded).
Same issue if I create CSV.

**Comment by benkeen** [comment]
Thanks @tempelmann. I'll fix this in the next release.

**Comment by benkeen** [comment]
Note to self: couple of things wrong here:
- looks like the initial import into the DB doesn't set it as UTF-8. 
- the "new window/tab" doesn't include the appropriate headers so it always appears as plain text.
