### ISSUE TITLE
Date help info doesn't appear

### ISSUE THREAD

**Issue by vaindil** [benkeen/generatedata#313]
When I click on the help for Date, the descriptions don't appear. I've highlighted several rows in the screenshot below to show they're not there at all (not the same color as the background or anything).

![screenshot](https://cloud.githubusercontent.com/assets/771134/10586989/0ec773a0-766d-11e5-81fa-f065a47e44a3.PNG)

**Comment by benkeen** [comment]
Thanks @vaindil, not sure what's going on there. I just released 3.2.2 and plan on updating the main website with the new version soon. I'll look at it then.

**Comment by benkeen** [comment]
This was fixed in 3.2.4. If you spot any more errors, just re-open this ticket or create another. Thanks!
