### ISSUE TITLE
Can not see any plugins in plugin installation page.

### ISSUE THREAD

**Issue by vishalbasnet23** [benkeen/generatedata#315]
All the plugins that should appear on the plugin installation page is hidden and if i hit install plugins button it is throwing following error log on the console.Please mention the way around this issue. Thank you
"pluginManager.js:34 Uncaught TypeError: Cannot read property 'errorHandler' of undefined"

**Comment by tr4nquility** [comment]
I second this.
If I click "Install Plugins" then the page will refresh, only to show the same condition.
Here is the screenshot :
![image](https://cloud.githubusercontent.com/assets/4945733/10753626/fc87a300-7cc4-11e5-8f67-1d20a9064502.png)

**Comment by benkeen** [comment]
Are you using the latest tag? The current master branch is in limbo at the moment while I work on the next release. Best to get the latest tag: https://github.com/benkeen/generatedata/releases

**Comment by tr4nquility** [comment]
Hi Benkeen,

Thanks for your reply.
Confirmed that installation using the latest release 3.2.1 finished successfully.
A quick question, if I want to apply the next release when it is available, will deletion of GenerateData folder suffice? Or I should drop its tables as well prior to installation?

Thanks.

**Comment by benkeen** [comment]
Sorry for the wait! Any time you upgrade, I'm afraid you'll need to start afresh: delete all old tables and do a fresh installation. Sometimes (depending on the change) this may not be necessary, but other times (like the new upcoming version) it will be.

I'd like to introduce a smoother upgrading path, but I don't have any immediate plans. Time, time, time!
