### ISSUE TITLE
User Account Login

### ISSUE THREAD

**Issue by tr4nquility** [benkeen/generatedata#316]
If a User has Email = "test@account.com" : password = "Standard1" and we login using Email = "test@account.com" : password = "Standard123456" ,  the result will be success.
In general, if we try to input a password which happened to contain the exact substring of "real" password of a particular User, then system will let you log in.

**Comment by benkeen** [comment]
Hmm... this seems somewhat improbable, but I'll check it out, thanks.

**Comment by benkeen** [comment]
I haven't been able to confirm this. Unless you enter the exact password string (both admins & regular users) the system will show you an error saying your login information is incorrect. 

Would you mind double-checking?
