### ISSUE TITLE
Date - Data generation is not correct

### ISSUE THREAD

**Issue by arunaps** [benkeen/generatedata#317]
Description: When tried to generate date data using the format dd-mm-yyyy, the date is downloaded as   
attached in the screen shots

Steps:

1. Provided column title
2. Provided data type
3. Selected example as 25-03-06
4. Under Options column edited the format to dd-mm-yyyy since I needed the date in this format

Actual: Date was downloaded as attached in the screenshot
![date format](https://cloud.githubusercontent.com/assets/15628973/10906539/44ef0326-8248-11e5-99d0-f10e698559a2.JPG)
![date format 1](https://cloud.githubusercontent.com/assets/15628973/10906543/4ae6d57e-8248-11e5-9b2e-87ff5f715355.JPG)

**Comment by benkeen** [comment]
Curious! It's probably Excel that's doing some weird formatting of the date. Could you try generating it in a different format (e.g. JSON) and see how that looks? Excel can be "smart" and try to do stuff like that.

**Comment by arunaps** [comment]
As per your direction I have tried generating the date using Json by following the above mentioned steps. I am getting the data in the same format which I reported for excel download via Json as well. Please see the screenshot.
![json date](https://cloud.githubusercontent.com/assets/15628973/10928941/5e6d5434-82d3-11e5-81c9-aa5b4f63268b.JPG)

**Comment by benkeen** [comment]
Ah! Sorry @arunaps. The replacement string is incorrect - but I see the documentation for the Date field type isn't showing up properly. I'll mark this ticket as a bug. 

Try entering this for the options string: `d-m-y`

**Comment by arunaps** [comment]
Many Thanks

**Comment by benkeen** [comment]
Note: the missing doc appears to only be on the main website.

**Comment by benkeen** [comment]
Will be solved in another ticket.
