### ISSUE TITLE
Error when you want to create a list of integer in SQL generator

### ISSUE THREAD

**Issue by Camilo193** [benkeen/generatedata#318]
When you want to generate something with a list and this is generated with ' ' and this made it Varchar and not Integer.
In the list option should have a integer option to no generate that in varchar form.
Sorry for my bad english.

**Comment by benkeen** [comment]
Great idea.

**Comment by Camilo193** [comment]
I can't create a list of integer, only Varchar.
I have another great idea.

**Comment by Camilo193** [comment]
Another idea:
A option when you want to generate the code in the same order in two list.
![generate](https://cloud.githubusercontent.com/assets/14241227/10983955/13c5da8e-83e4-11e5-867b-a413e69727ab.png)
