### ISSUE TITLE
email address generator

### ISSUE THREAD

**Issue by conradhagemans** [benkeen/generatedata#329]
Tip:

Have a good rendered email-address based on the generated first/lastname

I am using now compostite field with this code:

{$ROW3|lower}.{$ROW4|lower}@rc.dev.mydomian.com

$ROW3 is firstname, $ROW4 is lastname

**Comment by benkeen** [comment]
Nice one, @conradhagemans - I'll give this a new label: "Tips!" :)

**Comment by benkeen** [comment]
Adding this to 4.0.6. This is long overdue.
