### ISSUE TITLE
CSS problem center text on button

### ISSUE THREAD

**Issue by conradhagemans** [benkeen/generatedata#346]
I tried to get the text on the save button to be centred.
I cannot figure out where to change the code. I am not familair with SASS/CSS.

The dutch word for "Save" = "Opslaan" much longer word.

![screen shot 2015-12-16 at 14 54 19](https://cloud.githubusercontent.com/assets/9007177/11842657/4bae9666-a405-11e5-8067-0da3d3e339fc.png)

**Comment by Holiboat** [comment]
Changing padding on 
<button type="button" id="gdSaveBtn"></button>
from 
`padding:5px 17px`
to 
`padding:5px 0px;`
should do the trick

**Comment by conradhagemans** [comment]
Thanks. I changed the CSS files. I am not sure what the difference is between the sass versions and the compiled ones. I changed them booth.

**Comment by benkeen** [comment]
Thanks @conradhagemans! I've just merged your commit: https://github.com/benkeen/generatedata/pull/355

This'll be included in the next release (3.2.5).
