### ISSUE TITLE
add currentdate and currenttimestamp onto system

### ISSUE THREAD

**Issue by arcee123** [benkeen/generatedata#350]
Greetings,
I see that you use a data range to generate dates.
Can you use currentdate and currenttimestamp?
This will order the dates and timestamps by creation.
This helps alot when testing dimension tables.

Thanks.

**Comment by conradhagemans** [comment]
That is already supported by the composite datatype
just fill in {$smarty.now|date_format:'%Y-%m-%d %H:%M:%S'}
and it will the current data/time

**Comment by arcee123** [comment]
which field does that go into?
The start or end?
Thanks

On Wed, Dec 23, 2015 at 11:18 AM, Conrad Hagemans <notifications@github.com>
wrote:

> That is already supported by the composite datatype
> just fill in {$smarty.now|date_format:'%Y-%m-%d %H:%M:%S'}
> and it will the current data/time
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benkeen/generatedata/issues/350#issuecomment-166947941>
> .
>



-- 
Thanks
Evan

**Comment by arcee123** [comment]
never mind.  Thank you.
I didn't know about the composite datatype.
Thanks again.
You can close this issue.


On Wed, Dec 23, 2015 at 11:19 AM, Evan Cutler <arcee123@gmail.com> wrote:

> which field does that go into?
> The start or end?
> Thanks
>
> On Wed, Dec 23, 2015 at 11:18 AM, Conrad Hagemans <
> notifications@github.com> wrote:
>
>> That is already supported by the composite datatype
>> just fill in {$smarty.now|date_format:'%Y-%m-%d %H:%M:%S'}
>> and it will the current data/time
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/benkeen/generatedata/issues/350#issuecomment-166947941>
>> .
>>
>
>
>
> --
> Thanks
> Evan
>



-- 
Thanks
Evan
