### ISSUE TITLE
Copy Dataset

### ISSUE THREAD

**Issue by MrGiga** [benkeen/generatedata#352]
Currently you can't copy a data set. When hitting save it just renames it. Although the application keeps history, it is limited to 100.

**Comment by benkeen** [comment]
Regarding copying, yeah it's not very clear. To copy a data set, open up the Your Data Sets panel and select the data set row. There, in the footer of the dialog window will be the option to copy it. 

And yes, the history has a limit... though it should be 200. Hmm, I'll have to check that out!

**Comment by MrGiga** [comment]
My bad on the 100 limit, its actual 200. Thank you for replying so quickly!
