### ISSUE TITLE
Feature Request: Specify Random Generator Seed Value

### ISSUE THREAD

**Issue by stolp** [benkeen/generatedata#357]
Hi,

I have the requirement to generate the *same* set of random data in *different* formats (e.g. SQL and CSV).

For this I would like to specify the seed value of the random generator, so that each invocation of generatedata generates essentially the same data.

Is this feasible with the current implementation? Is there an alternative approach I might be missing?

Thanks for your hard work!

**Comment by conradhagemans** [comment]
I don't think that is possible for now.
Each time you start an export a new random set is generated.

**Comment by stolp** [comment]
Too bad. Thanks for the information!
