### ISSUE TITLE
Gender/Forename Link

### ISSUE THREAD

**Issue by Jhunter1** [benkeen/generatedata#358]
First of all I would like to thank you for making this fantastic tool! I've loved using it for filling my T-SQL databases i've been playing around with. This is more of a suggestion than anything.

Would you be able to link forenames to gender? For example if I want to add in 100 rows for 100 fake people, the forename is not linked to the gender and I get 'males' called 'Sarah' etc

Thanks

**Comment by conradhagemans** [comment]
I found a workaround with the existing functionality.
Field1 --> MaleName
Field2 --> FemaleName
Field3 --> Constant Loop 2 --> Male|Female
Field4 --> Composite --> {if $ROW3=="Male"}{$ROW2}{else}{$ROW1}{/if}

Now Field3 is the gender and Field4 has a correspondig firstname
