### ISSUE TITLE
Prompt To Download

### ISSUE THREAD

**Issue by iomari** [benkeen/generatedata#359]
Greetings,
I can't get "prmpt to download" to work. Whenever I try it, no matter how few records I use or which database option I use, after clicking generate I get a quick empty screen with the address "http://localhost/generatedata/generate.php" then it returns to the creation screen and that's it. No popup to ask where to save or any other dialog.
I'm also confused as to why after I generate without downloading, I get a screen with the generated data and no way to save it other that copy and paste which is  not very practical when the dataset is large. In fact, when I tried to copy and paste the generated data, it virtually choked my system for close to 30 minutes until I forcibly killed the process.

**Comment by conradhagemans** [comment]
Hi Iomari,
sorry to read that not verything is working. If you follow the guidelines everything should be fine. Maybe you can use a different browser to see if that works.
The behavior of the new screen with the data is as it should be. But only usefull for small datasets to get an imidiate idea of the exported data.

**Comment by iomari** [comment]
Thanks for your reply. I had tried it last night with a different browser and it worked. Don't know why the latest opera was giving me stress. I eventually got it working with a browser I never heard of called "Web".
BTW, I'm using Opensuse 13.2 if that is important.
I'm still confused though as to why I can't save to file after I generate using the first tab.

**Comment by conradhagemans** [comment]
3.2.4 is OK.
Can be closed.
