### ISSUE TITLE
Prompt to download in Excel

### ISSUE THREAD

**Issue by ashestovethesky** [benkeen/generatedata#363]
Morning, have a nice day, 

I just installed the script and worked fine. Nevertheless, when I tried the "prompt to download" option it worked for all outputs but excel. I don't know why, I tried some browsers more as previous post did, (safari, chrome, firefox and iceweasel) but with the same behaviour. Could you please give me a light to troubleshoot it?. I followed the installation instructions step by step and I got no errors. 

Thank you very much.

**Comment by derdeagle** [comment]
Hi @ashestovethesky,

please have a look at #360 - it might be the same problem.
Can you post the logs of your webserver? (error_log)
If you use SELinux check out `ausearch -m avc -ts recent` for denials or check `/var/log/audit/audit.log`

**Comment by conradhagemans** [comment]
Did a retest. 3.2.4 nicely exports to excel.
Can be closed.
