### ISSUE TITLE
Where are the APIs?

### ISSUE THREAD

**Issue by 53MikeC** [benkeen/generatedata#366]
I apologize in advance, but I'm new to a lot of this, and maybe it's covered somewhere I missed. 

I've installed the master.tar and the generatedata-3.2.4.tar several times, working out issues with my install.  I can't seem to find the APIs, the directory has index.html, process.php, and README.md.

The example on http://benkeen.github.io/generatedata/api.html suggests there's a directory /api/v/data but it doesn't seem to be installed for me.  I've added $apiEnabled = true; to my settings.php file.

I'd like to use the APIs to generate data and write them out to another process or even directly to a database, rather than download.

Thanks, MC

**Comment by benkeen** [comment]
Hey @53MikeC - no worries! 

Hmm, sorry you've had troubles with the install. Sounds like a pill. Any problems on my end, or just with your env? Let me know if there's a bug there.

Regarding the API, there's actually no `/v1/data` subfolders in `api` - it's just interpreted by the PHP to identify a valid API call. So don't worry that they're not there.

When you load up `http://[your domain]/api/v1/data` in your browser, do you see that error mentioned in the doc? http://benkeen.github.io/generatedata/api.html#enable

**Comment by 53MikeC** [comment]
Ahhh, that makes sense but the error i receive doesn't see below

http://xxx.xx.xxx.xxx/gendata/api/v1/data

Not Found
The requested URL /gendata/api/v1/data was not found on this server.
Apache/2.2.31 (Amazon) Server at xxx.xx.xxx.xx Port 80

**Comment by benkeen** [comment]
Hmm... possibly a bug. Looks like the API code isn't attempting to parse that URL. Let me tinker with this tonight after work. One hunch is that maybe the extra `gendata` subfolder is confusing it. It shouldn't, but it might be...

I'll get back to you!

**Comment by 53MikeC** [comment]
Just for grins, I moved all the code from the gendata subdir to the web root http://52.xxx.xx.xx/api/v1/data   and get the same error when trying the api.   THanks, Michael

**Comment by benkeen** [comment]
Rats. So much for that idea. ;)

**Comment by benkeen** [comment]
Sorry, I didn't get time to look into this tonight. Will try to get to it tomorrow.

**Comment by conradhagemans** [comment]
I think that the solution is simple. The .htaccess file is not executed because of the Apache settings.
You have to apply the setting "AllowOverride All" to the directory where GenerateData is installed.

**Comment by benkeen** [comment]
Oh nice one! It works for you? If you have a spare moment, I wouldn't mind a PR & I'll check it over and merge.

**Comment by conradhagemans** [comment]
Hi benkeen,
This morning I looked into it. I switch the API on to test. And yes I had the same problem as 53mikeC.
After some playing around with the .htaccess file I noticed that it was not being used. I found out that you have to configure the config file from Apache to tell Apache to Allow Apache the follow the Rewrite rule in the .htaccess file from generatedata.
I have installed generatedata in the gen2 folder under the root of my webserver.
I changed in the /etc/apache2/sites-available/default.conf the following section into:

<Directory /var/www/html/gen2>
                  Options Indexes FollowSymLinks Multiviews
                  AllowOverride All
                  Order allow,deny
                  Allow from all
                  Satisfy Any
</Directory>

Restart Apache after the changes.
The the API works. 
If you use SSL then you have to change it in the default-ssl.conf file.
In wich file you have to change depents on how the server is setup and on what operating system its runing.

So no PR needed. Just add in the readme or setup guide to add the line "AllowOverride All"

Thats it.

**Comment by 53MikeC** [comment]
Thanks!  Michael

**Comment by conradhagemans** [comment]
I think this one can be closed.

**Comment by benkeen** [comment]
Thanks, @conradhagemans!
