### ISSUE TITLE
Duplicate Names

### ISSUE THREAD

**Issue by m-p-g** [benkeen/generatedata#368]
I used this tool to create 20,000 company names, but for my dissapointment the names are NOT Unique, so I can't use this list. When I tried the sample, 100 they were all unique. 

How can I create unique company names?

**Comment by benkeen** [comment]
Sorry @m-p-g. :) No, company names don't ensure uniqueness. I've had this request a few times for different data types, so I'll jot it down as a feature request.

There really aren't options that I can think of within the script itself, though, beyond hacking the alphanumeric data type or something really kludgy. I'd suggest post-processing the generated data to filter out duplicate rows. 

Sorry about that!
