### ISSUE TITLE
Documentation and in app help does no explain how to create nested/tree xml output

### ISSUE THREAD

**Issue by MartynBedford** [benkeen/generatedata#372]
I have been through the docs and the in app help and can't work out how to create a nested / tree structure in my xml output, could you provide an example of how to achieve this.

It would be nice to import an XSD as a starting point for generating XML data.

**Comment by conradhagemans** [comment]
I don't think it's possible.
The system produces a none relational file.
I asume you are looking for a 1:Many file.

**Comment by benkeen** [comment]
You can use the Custom XML format option to do something along these lines - but only to change the structure of the generated XML. You can't have, for example, 100 rows of data, and within each row, a subgroup of 100 rows of different data.
