### ISSUE TITLE
Impossible to update an account

### ISSUE THREAD

**Issue by Kralock** [benkeen/generatedata#373]
We can't update an account.

Scenario : 
- Create an account
- Edit this account
- Modify the name
- Save it
- A pop up appear with "this account already existed"

![capture d ecran 2016-03-30 a 14 15 58](https://cloud.githubusercontent.com/assets/10655148/14141849/092967ce-f682-11e5-9e02-498f58900009.png)

**Comment by conradhagemans** [comment]
Hi Kralock,

Just did a test. I can confirm that this problem exists.
I will look into a later this week.

**Comment by conradhagemans** [comment]
Looked into the code.

In the file accountManager.js there is a function _openEditAcountDialog. This functions calls _onClickCreateAccount. Should be _onClickUpdateAccount. But this function doesn't exist.

I will see if I can fix it. But this is not my code so a bit hard to find the loop.

**Comment by benkeen** [comment]
Curious! Yes, that looks very wonky indeed - looking back over the history, I can't track down at what point it worked. @conradhagemans, I'll just add in the necessary functionality.

**Comment by benkeen** [comment]
Fixed. Will be in the next release.
