### ISSUE TITLE
CSV exportType : API :  eol option is not working and is always defaulting to \r 

### ISSUE THREAD

**Issue by mannem** [benkeen/generatedata#377]
https://github.com/benkeen/generatedata/tree/3.2.4/plugins/exportTypes/CSV

eol: the end of line character to use. For this setting, pass a string corresponding to the eol you want to use: Windows, Unix or Mac. These correspond to \r\n, \n and \r respectively.

However this doesn't appear to work when queried(POST) via API. It works fine from web UI though. The new line is always defaulting to '\r'.

**Comment by benkeen** [comment]
Sorry for not getting back to you sooner, @mannem. You're quite right, this is a bug. I'll include a fix for this in the next release. 

If you need it right now, you can make the patch yourself:
- edit the `plugins/exportTypes/CSV/CSV.class.php` file and change line 111 from:
```php
$type = $this->userSettings->export->eol;
```
to:
```php
$type = $this->userSettings->export->settings->eol;
```

Thanks for the bug report!
