### ISSUE TITLE
Limit the length of characters for e-mail

### ISSUE THREAD

**Issue by soke1556** [benkeen/generatedata#383]
Sometimes the e-mails are too long and it just doesn't work on most of the software that will import the data into. Limiting the amount of characters in the user part of the email will suffice.

**Comment by benkeen** [comment]
Fair point. According to the specs, emails are limited to 254 characters. I'll flag this as a bug to ensure the emails never get longer than that.

**Comment by benkeen** [comment]
Fixed. That said, I was unable to reproduce the problem. I found even setting a max length of 80 chars was exceedingly unlikely to occur. But I didn't check the entire contents of the random data file from which the emails were generated, so it's possible it could happen.
