### ISSUE TITLE
Unable to Set Password After Donating

### ISSUE THREAD

**Issue by mhmoore12** [benkeen/generatedata#386]
After donating and registering, I'm unable to complete registration and set a password. I get a blank screen at  http://www.generatedata.com/complete.php?id={id}.

Server returns 200 OK.

**Comment by benkeen** [comment]
Hi @mhmoore12, I'm sorry about that! If you click on the [login] link on the generatedata.com homepage, then use the password reminder feature - does that send you an email to reset your password? (Check your spam folder). If not, send me a note at ben.keen@gmail.com with the email you used to donate and I'll set it all up. 

Sorry for the fuss!
