### ISSUE TITLE
Can't install plugins 

### ISSUE THREAD

**Issue by aswatts** [benkeen/generatedata#387]
all data types, export types, and countries checked, but error is:

"Uh-oh.
Please select at least one Data Type.

**Comment by benkeen** [comment]
Hi @aswatts - could you provide a few details about the environment in which you're trying to install the code? PHP version, MySQL version, server type.

**Comment by stefanproell** [comment]
I have the same issue. I am using MySQL 5.7, Php 5.6 and Debian 8.

`mysql> select version();
+-----------+
| version() |
+-----------+
| 5.7.18    |
+-----------+
1 row in set (0.00 sec)
`
`
root@0dcc970436af:/var/www/html# php --version
PHP 5.6.30 (cli) (built: Mar 21 2017 23:01:57) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
`
in a Docker Debian GNU/Linux 8 environment.

**Comment by benkeen** [comment]
I think this issue was resolved a while back. Just comment if you or anyone else encounters the problem.

**Comment by BradPenwarden** [comment]
Any suggests as to what would cause this? MySQL 5.1.73, centos6 , php 5.3.3.
