### ISSUE TITLE
Nigerian data

### ISSUE THREAD

**Issue by oghenez** [benkeen/generatedata#400]
Hello, i must commend you for your beautiful work, I love it and make use of it often.
However it would be really nice if Nigerian data  (Names, street, state, phone) can be included, what can i do?

**Comment by benkeen** [comment]
Thanks @oghenez! For that, you'll need to add a Country plugin. Give this section a read over: 
http://benkeen.github.io/generatedata/countryPlugins.html#add_your_own

That explains how to create a new plugin which you can use for Nigeria. Let me know if it's not clear at all, or you get stuck on anything.

**Comment by benkeen** [comment]
Closing. We have had a Nigeria country plugin for some time.
