### ISSUE TITLE
Save function doesn't save all row settings.

### ISSUE THREAD

**Issue by biiconsulting** [benkeen/generatedata#401]
I've tried this a couple of times and have been able to recreate the behavior each time - latest editions of Chrome and Edge browsers.

Clicking the save saves all the rows, but not the details about the row.  Here's a screen cap of the saved content:

![image](https://cloud.githubusercontent.com/assets/1614006/22444715/658c592a-e701-11e6-9b88-c43705a4ce1a.png)

After saving with no errors displayed I try to re load the dataset. This is what the loaded dataset looks like:

![image](https://cloud.githubusercontent.com/assets/1614006/22444653/1f125f1c-e701-11e6-9f95-ad8c42539ad8.png)

This isn't a huge deal with 8 rows, but I found it after saving one with 35 rows.

Let me know if there's something else I can do to help troubleshoot.

**Comment by raiderj** [comment]
Seems like any rows with a "$" cause this issue? Seeing it on 3.2.7. Don't recall seeing it on 3.2.6 though.

**Comment by raiderj** [comment]
Also, the number of records to generate is not saved with a data set. Would be a nice to have feature if that's not there.

**Comment by benkeen** [comment]
Hmm, thanks guys! I'll take a look at this this weekend.

**Comment by benkeen** [comment]
Sorry for the wait - my weekends seem to keep filling up! It seems to be an issue with the Personal Number plugin, I'll include a patch for this in the next release (hopefully this weekend).

**Comment by benkeen** [comment]
Fiddly one! I just committed a fix. This'll be in the next release - may be a day or two until I can get to it.
