### ISSUE TITLE
"Uh-oh." message from step 1

### ISSUE THREAD

**Issue by BillAdama** [benkeen/generatedata#403]
Hello,
I'm unable to pass step 1: after filling the forms with correct data when I click "continue" I get an "Uh-oh." message and I'm unable to go on. I can connect via command line and via a sample php file using msqli.

I'm running Apache 2.4.25, PHP 7.0.15 and mariadb 0.1.21 under Fedora 25, can you help me fixing this error?

**Comment by ryanwcraig** [comment]
Are the permissions on the /cache folder set to 777?

**Comment by ryanwcraig** [comment]
You'll also probably need to create the settings.php file, but it'll yell at you in another step to do that with the lines it provided.

**Comment by BillAdama** [comment]
Just created the settings.php file and populated it using the example one and it worked!
Thanks you!
