### ISSUE TITLE
Question - Not really an issue ... installation item.

### ISSUE THREAD

**Issue by glad2badad** [benkeen/generatedata#409]
I'm looking for the right place to ask a question about installation of generatedata.  Is there a forum for this somewhere?

In case it can be answered here I'll ask.  Newbie to some of this ... trying to install generatedata on a Linux OS.  I have Apache Web Server, PHP, and MySQL installed.  The default Apache web page comes up, etc... so I think that's all fine.  

I unzipped the generatedata file into /usr/shared/generatedata ... (also tried it at /var/www/generatedata).  How do I get the install script to trigger or run?  Using http://localhost/<various combinations> and nothing ...

Did I unzip incorrectly?  Should a certain file be accessed directly?

Any help please?  Either with the above questions directly or with a forum link?  The user / dev documentation for generatedata doesn't cover this low level (beginner) type question.

Thank you.

**Comment by endo64** [comment]
Your default Apache web page probably shows /var/www/html so you can delete all files there and move generatedata files (not the folder itself the files inside the folder) into that folder then you should see the generatedata page (http://localhost/generatedata/install.php) and complete the installation.

There are better options like creating a vhost configuration and add a line to your host file like "127.0.0.1  generatedata.local" so you can connect by typing http://generatedata.local on your browser's address bar.

**Comment by glad2badad** [comment]
Thank you.  Yes, I believe I need to tweak a couple of things - including what you've mentioned.  Will try again, using your suggestion, when I get home tonight.  :-)

**Comment by glad2badad** [comment]
@endo64 ... Once I exposed the files directly to the main web directory and called up install.php, everything worked as needed.  I'm all set up and running the program now.  :-)  Next up ... working with the API.

**Comment by endo64** [comment]
@glad2badad Glad to hear that! Congratulations!
