### ISSUE TITLE
API Enabling does not work

### ISSUE THREAD

**Issue by denbekkerpas** [benkeen/generatedata#420]
Hello,

we installed generatedate with puppet, basically what it does
- installs apache 2.4 and php 5.6.30
- installs mysql
- download the latest generatedata.zip
- there is a template for the settings.php

It works good, but the only which does not work is the API. We are using Version 3.2.5 and the template looks like this:

$dbHostname     = 'localhost';
$dbName         = "generatedata";
$dbUsername     = "generatedata";
$dbPassword     = "$password";
$dbTablePrefix  = 'gd_';
$encryptionSalt = 'CYG';
$apiEnabled     = true;

When we try to access the API we are getting a 404, (/api/v1/data was not found on this server.) Does the API maybe need some extra php packages ?? Or was the API in someway not generated well ??

Could someone please help me ?

**Comment by glad2badad** [comment]
I added a .htaccess file to my main web directory.  In it I added rewrite conditions ...

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule api/v1/(.*)$ api/process.php?request=$1 [QSA,NC,L]
</IfModule>
```

In your httpd.conf file you'll also need to enable mod_rewrite.so by uncommenting the LoadModule line for that.

Additionally, you will want to add directory rules for the location of your main web page directory.
For example: 
```
<Directory "/your/webpage/homedir">
Options Includes Indexes FollowSymLinks
AllowOverride All
Require all granted
</Directory>

```
I found most of the above items by running various search terms (i.e. "Googling").  :-)

Good luck.

**Comment by raderjuber** [comment]
Thanks for the notes on how to update httpd.conf. On AWS Linux my .htaccess file was already updated, but https.conf needed to be adjusted. Would suggest this be added to the API documentation page, I wouldn't have figured it out otherwise.
