### ISSUE TITLE
Error Use Statement with Non Compound Name PDO has no effect in {PATH}\ressources\classes\Database.class.php on line 8

### ISSUE THREAD

**Issue by Shabasha** [benkeen/generatedata#423]
Once downloaded , unzipped and installed to C:\Program Files\Apache Software Foundation\Apache HTTP Server\htdocs\  i got this error : 

Warning: The use statement with non-compound name 'PDO' has no effect in C:\Program Files\Apache Software Foundation\Apache HTTP Server\htdocs\generateData\resources\classes\Database.class.php on line 8

Any help ???

**Comment by Shabasha** [comment]
Warning: The use statement with non-compound name 'PDOException' has no effect in C:\Program Files\Apache Software Foundation\Apache HTTP Server\htdocs\generateData\resources\classes\Database.class.php on line 8

**Comment by benkeen** [comment]
Ah! `master` contains the latest, unfinished code. To download the app, download the latest tags from here: https://github.com/benkeen/generatedata/releases

Mind closing this & the other tickets? Thanks @Shabasha!
