### ISSUE TITLE
Error Use Statement with Non Compound Name PDO Exception has no effect in {PATH}\ressources\classes\Database.class.php on line 8

### ISSUE THREAD

**Issue by Shabasha** [benkeen/generatedata#424]
Another issue found : 

Warning: The use statement with non-compound name 'PDOException' has no effect in C:\Program Files\Apache Software Foundation\Apache HTTP Server\htdocs\generateData\resources\classes\Database.class.php on line 8

**Comment by Hans0460** [comment]
Did you solve the problem?
To me it has happened the same and I do not know what to do :(

**Comment by benkeen** [comment]
Heya - yes, just download the code from one of the tags/releases, not master. Master is for current development work. 

This is clearly confusing a few people though, so I'll move my dev work into another branch this weekend. Sorry about that!
