### ISSUE TITLE
Fatal Error : [] Operator Not Supported for Strings in {PATH}\index.php(22)

### ISSUE THREAD

**Issue by Shabasha** [benkeen/generatedata#425]
After Installed and Created Database and Executed Script to Install Plugins , and then Followed all the Steps to start using the application , i got the following error :

Fatal error: Uncaught Error: [] operator not supported for strings in C:\Program Files\Apache Software Foundation\Apache HTTP Server\htdocs\generateData\resources\classes\ExportTypePluginHelper.class.php:203 Stack trace: #0 C:\Program Files\Apache Software Foundation\Apache HTTP Server\htdocs\generateData\index.php(22): ExportTypePluginHelper::getExportTypeCSSIncludes(Array) #1 {main} thrown in C:\Program Files\Apache Software Foundation\Apache HTTP Server\htdocs\generateData\resources\classes\ExportTypePluginHelper.class.php on line 203

Did you think to fix this error in the next release ?

**Comment by glad2badad** [comment]
Yep ... that's a bug.  Check Issue #410 (array to string fails when attempt to use as array comes back around) - I wrote a quick fix in there to get past it.

**Comment by benkeen** [comment]
Thanks @Shabasha and @glad2badad - yeah that was a bug. I just patched master and I'll release a new version shortly.
