### ISSUE TITLE
Invalid Column Name

### ISSUE THREAD

**Issue by gilfordtan** [benkeen/generatedata#426]
I have a MySQL table with column names, "_id", "_ctime", "_mtime". I have created and have been using this table for a while. And when I generate data to test it, it gave me invalid column name error as shown in the screenshot here: [http://i.imgur.com/m8AmGCM.png](http://i.imgur.com/m8AmGCM.png)

Can you explain how are they invalid even though I can create and use the table without issue?

**Comment by benkeen** [comment]
Hi @gilfordtan, ah thanks! Sorry about that - the validation being used is incorrect. I've patched it locally and I'll include it in the next version to be released later today.
