### ISSUE TITLE
Internal server error 500 at create user stage - Uh-oh

### ISSUE THREAD

**Issue by shalabiahmed** [benkeen/generatedata#427]
Hi All,
The install.php passed the stage of writing settings to settings.php.
The 2nd stage ,create user,  the browser displayed error message "Uh-oh".

The chrome debugger showed internal server error 500.

The php log file might indicates that the settings table does not exist.
Do I have to create settings table in the database? what is the structure of the table?

here is the php log with the error. I appreciate your help

======
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdata.gd_settings' doesn't exist in C:\inetpub\wwwroot\generatedata-master\resources\classes\Database.class.php:59 Stack trace: #0 C:\inetpub\wwwroot\generatedata-master\resources\classes\Database.class.php(59): PDO->prepare('\n\t\t\tSELECT sett...')
#1 C:\inetpub\wwwroot\generatedata-master\resources\classes\Settings.class.php(42): Database->query('\n\t\t\tSELECT sett...') #2 C:\inetpub\wwwroot\generatedata-master\resources\classes\Core.class.php(310): Settings::getSetting('installationCom...') #3 C:\inetpub\wwwroot\generatedata-master\resources\classes\SessionManager.class.php(13): Core::checkIsInstalled()
#4 C:\inetpub\wwwroot\generatedata-master\resources\classes\Core.class.php(509): SessionManager->__construct() #5 C:\inetpub\wwwroot\generatedata-master\resources\classes\Core.class.php(130): Core::initSessions() #6 C:\inetpub\wwwroot\generatedata-master\resources\classes\AjaxRequest.class.php(72): Core::init('installatio in C:\inetpub\wwwroot\generatedata-aster\resources\classes\Database.class.php on line 59

**Comment by BrayanLP** [comment]
hi @shalabiahmed , I have the equal mistake, you have the solution?

**Comment by shalabiahmed** [comment]
I'm not sure yet about the solution . But, the log file states that gd_settings table is missing. But, I need the help of getting the field names of the table?

**Comment by glad2badad** [comment]
Installation.class.php file ... around line #85 are where the db construction starts taking place.  Around line #134 is where the settings table is created.  

Field names are: 
setting_name varchar(100) NOT NULL
setting_value text NOT NULL
UNIQUE KEY setting_name (setting_name)

**Comment by shalabiahmed** [comment]
The code drops all the tables in DB if exist

$rollbackQueries = array(
			"DROP TABLE IF EXISTS {PREFIX}cities",
			"DROP TABLE IF EXISTS {PREFIX}configurations",
            "DROP TABLE IF EXISTS {PREFIX}configuration_history",
			"DROP TABLE IF EXISTS {PREFIX}countries",
			"DROP TABLE IF EXISTS {PREFIX}regions",
			"DROP TABLE IF EXISTS {PREFIX}sessions",
			"DROP TABLE IF EXISTS {PREFIX}settings",
			"DROP TABLE IF EXISTS {PREFIX}user_accounts"
		);

		// start off by clearing out the DB, just in case. For this, we just run the rollback queries (used
		// below, in case of an SQL error)
		Core::$db->query($rollbackQueries);

**Comment by hraph** [comment]
Anything new about this issue?  I got the same problem..

**Comment by benkeen** [comment]
Hey all - I'm really sorry for the confusion. The `master` branch is for current dev work & is currently incomplete. Please download the latest version from one of the releases here:
https://github.com/benkeen/generatedata/releases

**Comment by shalabiahmed** [comment]
Thanks Ben. That solved the problem. 
Question: how to add a "computed" field to distinguish between genders? i.e if we selected a male name, the field should state "Male" as example.

**Comment by benkeen** [comment]
See: https://github.com/benkeen/generatedata/issues/428 for the last question asked here.
