### ISSUE TITLE
Installation hangs at step 4 (Plugins)

### ISSUE THREAD

**Issue by YonatanG95** [benkeen/generatedata#433]
Hi,

I'm having an issue with step 4 - plugins.
When clicking "Install plugins" I'm getting an "Uh-oh" error with no details and the installation hangs.
Looks like this:
![untitled](https://user-images.githubusercontent.com/29713825/29997943-739ad12e-9028-11e7-8053-1ce565df3c33.png)

I'm using server 2008 R2
PHP 5.3
SQL 5.7 (tables where created)

**Comment by benkeen** [comment]
You mentioned Server 2008? MS SQL server? I'm afraid generatedata only runs on MySQL. Sorry about that!

**Comment by MikeGreyDog** [comment]
I have the same picture with MySQL.

**Comment by BradPenwarden** [comment]
Any one have luck with this issue - php 5.3.3 and mysql?

**Comment by Opalschleifer** [comment]
same issue here with php 5.3.29 and mySql 5. :(

**Comment by yujiaao** [comment]
same issue here with PHP 7.0 and MySql 5.5

**Comment by MrMannSP** [comment]
I'm hitting the same issue with MySQL 5.7 but realised IIS was picking up the older version of PHP, Upgrading to version 7 fixed it for me.
