### ISSUE TITLE
Auto-save data set even if you're not logged in, so you can save it after logging in

### ISSUE THREAD

**Issue by benkeen** [benkeen/generatedata#435]
This applies to the website but could be handy for the regular script as well. Perhaps auto-saving it in a temporary location in the DB for up to 1 day, then after logging in prompts you to load it?

**Comment by briannoyes** [comment]
Yes! I've done this to myself several times in the last few days working on a project - go through and get all the column definitions I want and then go to change the rows output and realize I'm not logged in and doing so loses all my work. Very annoying time waster.

**Comment by benkeen** [comment]
This was added in v4. Now it automatically saves as you go so in case of page refresh / crash, nothing is lost. Closing.
