### ISSUE TITLE
Wrong values generated 

### ISSUE THREAD

**Issue by GabrielRodriguesS** [benkeen/generatedata#444]
The best way to explain this error is with an example: 1 field type date and 3 fields type "parent row id", in fields "parent row id" values ​​of type date are inserted, see the lines from output:
subtitle:
age = field date 
person_id, breed_id, postage_id = parent row id

![issue git](https://user-images.githubusercontent.com/15824190/34804034-a18d1c0e-f65d-11e7-8db0-80edfa519180.JPG)

note that there are many values ​​of type date in the fields of other types.

**Comment by endo64** [comment]
What happens if you try as:
```
id = int
age = field date
person_id, breed_id, postage_id = parent row id
```
Does it work correctly in that case? Parent row id may require the first column is primary key.

**Comment by GabrielRodriguesS** [comment]
It worked, thank you and sorry for the delay in responding 😄
