### ISSUE TITLE
Help wanted: Calculate fields 

### ISSUE THREAD

**Issue by MvErven** [benkeen/generatedata#446]
Hello, I would like to have a calculation of fields.

Case 1)
Row 1 contains a date - range 01/01/2017 till 01/01/2019
Row 2 contains a custom list - 14|21|30|60 (payment term)
How do I get a composite 'date' from {$row1+$row2} - it now calculates the days from row1 + row2 instead of giving me the date + days in a date format

Case 2)
Almost same as Case 1, except for currency.

Row 3 invoice amount - currency between 1000 and 2.000.000
Row 4 amount paid - currency between 10 and 2.000.000
How to get {Row4} may not be larger then {row3} 

The smarty website it too complex for me.
Thanks in advance.

**Comment by MvErven** [comment]
I'll take the composite field. Although not ideal, it handles my needs for a few months.

**Comment by flashinpan** [comment]
I have this exact same need. How did you solve it?

**Comment by MvErven** [comment]
today I am not at work so I can't answer. tomorrow I will show you my example/ work around.



Verzonden vanaf mobielOp Alan Luckow <notifications@github.com>, schreef 15 mei 2019 10:12 p.m.:I have this exact same need. How did you solve it?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/benkeen/generatedata/issues/446?email_source=notifications\u0026email_token=AEISGPF6RKLH3IDPOUZAPLDPVRVBTA5CNFSM4EO4WHQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVPZ5II#issuecomment-492805793",
"url": "https://github.com/benkeen/generatedata/issues/446?email_source=notifications\u0026email_token=AEISGPF6RKLH3IDPOUZAPLDPVRVBTA5CNFSM4EO4WHQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVPZ5II#issuecomment-492805793",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by flashinpan** [comment]
Wow, that would be great! Any time it is convenient I would surely appreciate your help.

I'm using the web app and it seems it only lets me do a calculation in the composite field if the numbers are of equal type, and it won't do a calculation with a number that was the result of another calculation. So I can't calculate something like "net pay" and then multiply that to get "year to date Pay", things like that.

**Comment by MvErven** [comment]
(Almost forgot. Busy day today)

I have done it with the downloaded version. Only trouble is exporting datasets wich is not supported (yet) Maybe I can explain with these screenshots. Only disadvantage is the date **range**. This one I must set manually every time again. (Import is now done only periodically) That's why I also asked for a scheduler ;)

Please have a look at the screenshots. (naming is dutch, but I'll can translate them monday or thuesday)
This is a "combined" (debtors+invoices) test file because I needed the invoicenumbers to match the debtor number(s)

![datagen1](https://user-images.githubusercontent.com/17900348/57935343-dfc8a280-78c1-11e9-88b8-a12aad30ed39.png)
![datagen2](https://user-images.githubusercontent.com/17900348/57935344-dfc8a280-78c1-11e9-83c9-13b906870f39.png)

Hope this may give you a start or at least some insight how to use these date ranges. 
Cheers!

**Comment by flashinpan** [comment]
This is great! Thanks for posting the screenshots. I'll see if I can sort them out.

**Comment by MvErven** [comment]
@flashinpan Any luck sorting them out?

**Comment by MvErven** [comment]
Well, leave a reply when you ready. I'll close this issue.

**Comment by flashinpan** [comment]
Yeah, I sort of gave up on it. I was making many changes within the web app, but they never saved. It would save part of it, but not all of it. I subscribed and all that so it should have worked. I couldn't spend time on it if I was going to have to re-do it every time. I had to look for another solution. Thanks for you help though.
