### ISSUE TITLE
 changing the number of generated rows in demo site by browser developer tools

### ISSUE THREAD

**Issue by mohammadgolche** [benkeen/generatedata#456]
![1](https://user-images.githubusercontent.com/40236016/41349668-d7d0e0ca-6f25-11e8-9296-69e64bf26fc3.jpg)
 changing the number of generated rows in demo site by browser developer tools

**Comment by benkeen** [comment]
Thanks @mohammadgolche - there was a server-side check as well, but it seems to be being bypassed. I'll check it out!

**Comment by benkeen** [comment]
This'll be included in the next site update (today).
