### ISSUE TITLE
generatedata v4: what would you like to see?

### ISSUE THREAD

**Issue by benkeen** [benkeen/generatedata#462]
Time to start planning for version 4! In the next few months I'll be wrapping up a big update to formtools.org (one of my other larger projects) and I want to return to generatedata to do some spring cleaning and maybe undertake some larger improvement.

On my list is:
- reduce the application size, faster load times
- rewrite the FE in React or Vue, drop jQuery and older libs. GraphQL? 
- update the build process to webpack or rollup
- Make site responsive
- general application style/theme updates
- _Performance, performance, performance_ for the data generation.
- Somehow allowing embedding generatedata into other applications & having a standardized return format for the data.

Also, do we want to keep the BE in PHP? Gotta say, having a node implementation would be terrific .- and almost certainly more performant. 

What would you like to see? Feel free to thumbs up the issues flagged as feature suggestions here:
https://github.com/benkeen/generatedata/issues?q=is%3Aissue+is%3Aopen+label%3A%22Feature+Request%21%22
or comment below.

**Comment by flashinpan** [comment]
Ben,

I left this comment on the other site. Not sure it went though, I apologize if it duplicated. 

This web app is actually very cool. I subscribed immediately. It seems you have many of the formats covered. I love all the download options.

As far as feature requests, I guess I have two:

1) Be able to add a field that is additive from another field. For example, it you were doing pay stubs, and you wanted a random pay period. The beginning random date is no problem, but if the pay period is two weeks, then ending date needs to be two weeks from that first random date to make sense. Seems kind of esoteric but there are a lot of uses for this type of feature.

2) Having the ability to insert a random graphic, such as a person's face would be handy. There are sites like unsplash.com that provide the public domain people for free. 

Anyway, this app has been very useful to me. Thanks for putting the time in.

Al

**Comment by MvErven** [comment]
@flashinpan The current date is done with smarty. Have a look at #350 However I also do wish to see a +14 day and +30 days like you. (financial software - payment terms)

**Comment by flashinpan** [comment]
I tried the composite field in the browser app with a calculation such as:

{$ROW10*$ROW11}

But my values always come out as zero even though each row has a value. Is there some kind of syntax required AROUND this formula for the smarty code to be run?

Any Help surely appreciated!

Al

**Comment by MvErven** [comment]
When I look at the struggle I have with the API. My suggestion woulkd be: Export current or saved dataset to an API script?

**Comment by benkeen** [comment]
Closing. v4 is now in alpha here: http://generatedata4.com
