### ISSUE TITLE
Generate range with negative number

### ISSUE THREAD

**Issue by olton** [benkeen/generatedata#463]
Hi! First of thanks for your work!
If I want to generate a number of values in the range from negative value to positive value, I receive zeros.

**Comment by benkeen** [comment]
Hey @olton, sorry for not getting to this sooner. Could you describe how to reproduce this? 

The one thing I noticed was that you can't enter the number range in arbitrary order, i.e. a negative number first, then a positive one second. I'll patch that up to generate the numbers regardless of order.

**Comment by benkeen** [comment]
I've put in the patch to allow entering the number range in any order (low->high, high->low) which I think will patch this. If there's another issue I don't know about, let me know.
