### ISSUE TITLE
Oops, nothing to generate! Enter some data to be generated.

### ISSUE THREAD

**Issue by igonch1977** [benkeen/generatedata#475]
Script was installed on local Ubuntu server. When trying to generate data, get an eror:

Oops, nothing to generate! Enter some data to be generated.

![image](https://user-images.githubusercontent.com/25481544/57753857-d8549e00-76f5-11e9-9f0b-7b3f5d2594ad.png)

**Comment by MvErven** [comment]
You have not chosen any data type

**Comment by igonch1977** [comment]
Thanks. You are correct! It will be more clear to modify error text to something like: "Please select data type to generate data"

**Comment by MvErven** [comment]
Guess you may close this issue then ;)
