### ISSUE TITLE
Vanishing composite field calculations!

### ISSUE THREAD

**Issue by flashinpan** [benkeen/generatedata#476]
In the web app, I save my data set every time, but everything in my composite fields, my calculations, vanish when I re-open the data set! What's going on? I can't use it like this! Is there some limit to the number you can have?

**Comment by benkeen** [comment]
Hmm, that sounds like a bug. If the data set isn't sensitive, would you mind taking a screenshot of your configuration (i.e. the generate data page where you define the fields) so I could reproduce?

**Comment by flashinpan** [comment]
I'll send you a screen grab so maybe it will help you. I had to find another solution though since I can't afford to spend hours on something only to have the fields vanish. 

Here is the config:

https://www.dropbox.com/s/7k07njjskrsrwrf/screencapture-generatedata-2019-06-26-10_06_45.png?dl=0

**Comment by benkeen** [comment]
I totally understand, sorry about that! I appreciate the screenshot. I'll try reproducing it on my end.

**Comment by benkeen** [comment]
Thanks again @flashinpan, this seems to be a bug with the Organization Number component. I'll patch that up today.
