### ISSUE TITLE
NO mechanism to actually REGISTER on your website in order to save dataset :-( ... 

### ISSUE THREAD

**Issue by markvogt** [benkeen/generatedata#478]

**Comment by benkeen** [comment]
Hey @markvogt, did you donate? If so, and you didn't click "return to merchant", you should at least receive an email with a link to the registration page. But it DOES get swallowed up by spam filters so check your spam folder. If you don't have any luck finding it, email me at ben.keen@gmail.com and I'll look into it. Sorry for the fuss!

By the way, in case I misunderstood and you didn't donate, the application is all free and open source with download link and installation instructions here: http://benkeen.github.io/generatedata/install.html - you can save your data sets with that version too.

Hope this helps!

Ben
