### ISSUE TITLE
Online version is not working

### ISSUE THREAD

**Issue by zeeshanyshaikh** [benkeen/generatedata#509]
The online version of Generatedata is not working. I tried with http and https both. Attached is the screenshot for more clarity.

![image](https://user-images.githubusercontent.com/6223015/69540403-86e27100-0fac-11ea-9299-523fbb2cac3f.png)

**Comment by benkeen** [comment]
Hmm! Looks like it's ok for me on Mac/Chrome. What browser are you on?

**Comment by zeeshanyshaikh** [comment]
Working for Windows/Chrome but not on FF and IE

**Comment by benkeen** [comment]
Drat, I do apologize you're absolutely right. I'll get this fixed soon.

**Comment by benkeen** [comment]
The prod site is working again, sorry about that. 

I've patched this on the v3 branch and I'll include it in the next release.
