### ISSUE TITLE
How to enable IBAN Plugin

### ISSUE THREAD

**Issue by arcontechnologies** [benkeen/generatedata#510]
Hi,
I new to this app. I can see the IBAN plugin in the folder but it's absent from the GUI. Is there a way to enable it ?

thanks

**Comment by benkeen** [comment]
Bug! Looks like some of the data types are overriding one another with the order in which they're placed to appear. To make it show up, edit the `plugins/dataTypes/IBAN/IBAN.class.php` file and change this line:
```protected $dataTypeFieldGroupOrder = 100```
to 
```protected $dataTypeFieldGroupOrder = 103;```

I'll patch the code in the next v3 released to prevent this from occuring again. Thanks!

**Comment by arcontechnologies** [comment]
Got it. Thanks
