### ISSUE TITLE
Links leading to 404

### ISSUE THREAD

**Issue by PatoChyno** [benkeen/generatedata#511]
The links to READMEs in this article: http://benkeen.github.io/generatedata/api.html#readme_files lead to a 404 error. The links should probably start with something like: https://github.com/benkeen/generatedata/tree/3.4.1/plugins (3.4.1 or other version instead of "master").

**Comment by benkeen** [comment]
Thanks @PatoChyno, yeah - ever since I swiped master for the new v4 work, those links will be incorrect. I'll update it, thx!

**Comment by benkeen** [comment]
Updated. Thanks!
