### ISSUE TITLE
generatedata v4 progress

### ISSUE THREAD

**Issue by benkeen** [benkeen/generatedata#514]
Hey! I've moved notes about the v4 rewrite to here:
https://github.com/benkeen/generatedata/discussions/categories/v4-notes

**Comment by amardeshbd** [comment]
I just want to say this is an awesome project! I used it 7-8 years ago when I used to work on web. Didn't know it's open source and available in GitHub. 

New UI looking clean! 👍

**Comment by benkeen** [comment]
Thanks a lot @amardeshbd! It's coming along...

**Comment by boban-dj** [comment]
Hi, great work on the design so check off :rethink design for the umpteenth time...
yeah, really no need to redesign its perfect.
Would be great if you could add a placeholder image field as datatype. Like these:[https://loremipsum.io/21-of-the-best-placeholder-image-generators/](url)

**Comment by benkeen** [comment]
haha thanks :) The design isn't _toooo_ bad at this point!

That's a terrific idea, love it.
