### ISSUE TITLE
Deprecated: Function get_magic_quotes_gpc() is deprecated in $_PATH\generateData\library.php on line 50

### ISSUE THREAD

**Issue by Shabasha** [benkeen/generatedata#520]
Hello 

First of All sorry for my bad english 

I have Apache 2.41 VC16 64bit installed with PHP 7.4.0+ and MySQL 8.0.19

When i downloaded the latest version of generateData ( 3.4.1 ) , i found that the following message was thrown when i tried for the first time to start the installation from web browsing.

Deprecated: Function get_magic_quotes_gpc() is deprecated in $_PATH\generateData\library.php on line 50

In the meantime , waiting for any official replacement for this function that may be announced by PHP Community.

Are there anything wrong or do i miss something in my installation ? 

Please help !

**Comment by Shabasha** [comment]
I think that PHP7.4.X does not support anymore this function , is there any replacement for that ? or do i need to downgrade from PHP 7.4.x to 7.x ?

**Comment by benkeen** [comment]
Hey @Shabasha, sorry for not responding sooner! 

No worries, I'll release a patch release to address this. In the meantime, you can safely just remove these lines in your `library.php` file:
https://github.com/benkeen/generatedata/blob/v3/library.php#L49-L64

It was just to handle backward compatibility with very old PHP versions.

**Comment by benkeen** [comment]
Closing. Old issue.
