### ISSUE TITLE
Computed reference results in 'Array' instead of value

### ISSUE THREAD

**Issue by Qndrs** [benkeen/generatedata#530]
When refencing in a computed value to another row the calculated value is not displayed but the string 'Array'. This is also the case at the demonstration website. Maybe this is a PHP7.3 issue?
![image](https://user-images.githubusercontent.com/1015110/82129497-a4f29680-97c3-11ea-85eb-8a906d892a99.png)
![image](https://user-images.githubusercontent.com/1015110/82129498-a9b74a80-97c3-11ea-887c-4e81849409cb.png)

**Comment by benkeen** [comment]
Hmm, maybe so... this definitely worked at some point.

**Comment by Qndrs** [comment]
Yes it did. It work on my PHP5 installation but I had to upgrade the server to 7.3. Since it does return the object (array) my thought is it might be a depricated function or a twisty version issue.

**Comment by FutureLearningBV** [comment]
You can close this as a bug. It's an error on my side. When selecting data type 'Computed' I should have selected 'Composite'. It all works then. Computed needs a different syntax and also works with the right syntax.

**Comment by Qndrs** [comment]
You can close this as a bug. It's an error on my side. When selecting data type 'Computed' I should have selected 'Composite'. It all works then. Computed needs a different syntax and also works with the right syntax.
