### ISSUE TITLE
Helm chart for generatedata

### ISSUE THREAD

**Issue by dmirubtsov** [benkeen/generatedata#532]
Hi,

I wanted to install generatedata into Kubernetes cluster but didn't found helm chart for that.

I've prepared helm chart for easily install generatedata into [Kubernetes](https://kubernetes.io/) clusters. It based on the [mvisonneau/docker-generatedata](https://github.com/mvisonneau/docker-generatedata) docker image

https://github.com/dmirubtsov/generatedata-helm

Please add it to the readme, maybe it will be helpful for users

**Comment by benkeen** [comment]
Great stuff, thanks @dmirubtsov - will do.
