### ISSUE TITLE
Not able to access account on website

### ISSUE THREAD

**Issue by DanIntersectly** [benkeen/generatedata#537]
Hey Ben, just made a donation but not able to access the site. I'm not a Dev so need to use the web version. I pinged you an email as well. Cheers Dan

**Comment by DanIntersectly** [comment]
Please ignore - all sorted...

**Comment by benkeen** [comment]
Ooh drat, I just saw this after resetting your password - apologies! Check your email for the temporary password that it's been reset to. 

Thanks Dan!
