### ISSUE TITLE
Single quotes for MS SQL Server 

### ISSUE THREAD

**Issue by Newbie0007** [benkeen/generatedata#539]
Please include an option to generate 'Single quotes' and "Double quotes"
To make this data valid on different Databases SQL or server

Values must be in single quotes (' ')

as opposed to double quotes:  VALUES _**("Logan","Church","(419) 675-6085","38838185199","2021-01-03 11:40:51"),("Xander","Huber","(584) 484-4800","90347415399","2020-02-24 23:11:36"**_

**Comment by benkeen** [comment]
Will do. I'll add this in v4, demo'd here: https://site.generatedata4.com/

**Comment by benkeen** [comment]
Updated. 

![original](https://user-images.githubusercontent.com/512116/108155200-4a100780-7093-11eb-8aa1-3abdba8ee8cc.jpeg)
