### ISSUE TITLE
Allow character separation in custom lists (v4)

### ISSUE THREAD

**Issue by albertodiazsaez** [benkeen/generatedata#600]
Hi.
In the V3 you can insert a list with a String text separated with the '|' character. In V4 this functionality is lost since you have to press Enter after each element.

Since issue #319 is not developed yet, I have in a document custom lists (values separated with '|')  that I often use for my personal needs (for example list of Cities in my region that won't be very useful for the general user) and with V4 I can't use them.

![imagen](https://user-images.githubusercontent.com/40151953/116267277-90ad6c80-a77c-11eb-8b1a-7d6fd8b2a658.png)

Can the functionality of V3 be replicated in V4? For example with two fields: The List field and the Separator field, and if the String in the list contains the Separator Character, it will be divided when the user presses Enter?

Thanks.

**Comment by benkeen** [comment]
Hey @albertodiazsaez, good idea - this is needed. I'll update the Data Type to allow this. Thanks!

**Comment by benkeen** [comment]
Added. I'll include this in the next alpha site release (in the next day or two).
