### ISSUE TITLE
Generate valid address information

### ISSUE THREAD

**Issue by 9h87f497h4387b9** [benkeen/generatedata#642]
Allow the generation of random valid addresses within specified parameters, such as state.

Currently, the address elements are generated independently from each other, resulting in consistent address formats, but not valid addresses.

**Comment by benkeen** [comment]
Heya, actually this is done with the new version, found at it's temporary location here:
https://site.generatedata4.com

You can map country, region, city and postal code.

I'm having a few weeks off, but that'll become the new website + a downloadable form will be available at some point.

Ben
