### ISSUE TITLE
White Screen when the "fixed number words..."s count is changed

### ISSUE THREAD

**Issue by MuhammedCanKucukaslan** [benkeen/generatedata#644]
Sorry, I couldn't explain in words so here is the video capture.

https://user-images.githubusercontent.com/32893303/127629177-43c0b2b5-b0d3-4dc4-94bf-bc0b058be01a.mp4

ps. I've tried it in both Firefox and Edge browsers, using  —v4.0.0-alpha-20210608 version via https://site.generatedata4.com/generator .

**Comment by benkeen** [comment]
Fixed. I'll work on getting a release out shortly.
