### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by saadsaiyed** [benkeen/generatedata#667]
Can you please add Timestamps as well? Thanks.

**Comment by benkeen** [comment]
Hey @saadsaiyed! Actually both v3 and v4 support that.

For v3 (the current website), just use the "U" character: 
<img width="994" alt="Screen Shot 2021-09-11 at 8 57 33 AM" src="https://user-images.githubusercontent.com/512116/132953890-1ad0de7a-5231-41ae-b65c-0c5f9258f387.png">

For v4 (still currently in beta on the [preprod site](https://site.generatedata4.com/generator)) you can enter "t" or "T" for unix time (seconds) and unix time (milliseconds) respectively: 
<img width="1440" alt="Screen Shot 2021-09-11 at 8 59 18 AM" src="https://user-images.githubusercontent.com/512116/132953946-dd54ce3a-a3c1-4795-9364-674f75ce0b62.png">

**Comment by saadsaiyed** [comment]
That was quick, thanks a lot.
