### ISSUE TITLE
Can not change the id ranges in update command

### ISSUE THREAD

**Issue by talhaamir4130** [benkeen/generatedata#686]
We should be allowed to change the id ranges, 

UPDATE `XXX` WHERE `id = 1` 

We must be able to choose ids to update

**Comment by benkeen** [comment]
Hi @talhaamir4130, thanks for the post! How do you picture those IDs being configurable? What IDs would you like to see there? 

To best honest, I originally added the "UPDATE" option many years back for the common scenario where you generate N rows of data, then don't want to TRUNCATE the table and re-insert, but can rely on an auto-increment field having been used in both places. In which case the IDs are always 1-N so UPDATE will always work. Pretty limiting though, agreed.

**Comment by benkeen** [comment]
Closing. This won't be done.
