### ISSUE TITLE
When generating a CSV data set, the UI spins and never generates records.

### ISSUE THREAD

**Issue by sscalisi** [benkeen/generatedata#687]
I registered for the tool a couple of days ago.  I'm attempting to generate a 1000 row csv data set with about 10 columns.  When I generate the data set, the UI spins indefinitely and never generates any rows.  I've tried both Chrome and Firefox.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/9418516/134385613-5e3703c1-1a22-4fd4-80b2-21aadb1eba90.png">

Chrome Version: 93.0.4577.82
Firefox Version:  92.0

**Comment by benkeen** [comment]
Apologies @sscalisi - this looks like a bug with the Number Range data type. I'll fix it and update the site tonight. Thanks for letting me know!

**Comment by benkeen** [comment]
Correction - it _was_ CSV, not the Number Range Data Type. I'll make a post here when it's been deployed to the website.

**Comment by benkeen** [comment]
The site has been updated now. Let me know if you still have problems! Thanks @sscalisi.
