### ISSUE TITLE
Column Names should be encapsulated

### ISSUE THREAD

**Issue by MarcusCulverTHL** [benkeen/generatedata#759]
I recently pulled a data set where I named the columns "phone-uk"

Because for SQL Server these weren't encapsulated in square parentheses the import of the data set failed due to hyphens being a reserved character. 

Column names (if abiding by best practise) should be qualified by square parentheses ( [phone-jp] ) to ensure the engine doesn't consider the hyphen as something else

**Comment by benkeen** [comment]
Sorry, I've been pulled into other things the last couple of months. Finally returning to this now, so expect an update in the next few weeks.

**Comment by benkeen** [comment]
I took a look at this and found a couple of issues, but encapsulating the column names seems to be working properly - see screenshot. I fixed the error - now it doesn't appear as invalid when you enter a column name like `phone-uk` with a hyphen. 

<img width="1195" alt="Screen Shot 2022-11-26 at 3 32 03 PM" src="https://user-images.githubusercontent.com/512116/204112931-5254a696-cee8-43b1-a7f3-c0d57c035ef8.png">
