### ISSUE TITLE
SSL Authentication Certificate will Expire soon

### ISSUE THREAD

**Issue by RHernandez44** [benkeen/generatedata#762]
Some browsers produce a warning saying not to trust this site due to its authentication
Renew SSL cert soon

**Comment by benkeen** [comment]
Thanks @RHernandez44... odd, I've kept the SSL cert up to date since releasing version 4. It's on an automatic update process, as is the older generatedata3.com domain. 

What browser were you using?

**Comment by benkeen** [comment]
Closing. Seems fine. Do ping me if you still see it / it occurs again.
