### ISSUE TITLE
Data Sets not deleted from account

### ISSUE THREAD

**Issue by mmr118** [benkeen/generatedata#788]
When trying to delete a saved `data set` from my account, the data set persists.

**Comment by benkeen** [comment]
Hey @mmr118, thanks for posting. I haven't been able to reproduce the problem, however. Are you seeing it on your own installation or on generatedata.com itself? 

Couple of other questions:
- does the problem occur for all data sets, or just one? 
- what browser are you using?

**Comment by benkeen** [comment]
Closing, but do re-open or comment if this problem is still around.
