### ISSUE TITLE
Cannot find module "../../_env" when running yarn startApp

### ISSUE THREAD

**Issue by Ultcrt** [benkeen/generatedata#806]
Hello, 

I get following error while running yarn startApp:
```shell
semantic error TS2307: Cannot find module '../../_env' or its corresponding type declarations.
```
#749 also mentioned the same error.

I think this error is caused by "yarn prod" script that executes "yarn build" after "grunt".

Maybe the "yarn prod" script should executes "yarn build" before "grunt", like:
```json
"prod": "cd client && yarn build && grunt && yarn webpackProd"
```
So that _env.ts is generated before executing "grunt".

**Comment by benkeen** [comment]
Thanks! I hate to say it, but I noticed this too & hadn't updated it. I'll update the script - I think I did the same fix.

**Comment by Ultcrt** [comment]
Cool, happy to know that bug is fixed! Thanks for the response and this amazing project!
