### ISSUE TITLE
Datasets not updating, not deleting

### ISSUE THREAD

**Issue by jfinighan** [benkeen/generatedata#829]
In my account:

- Deleting datasets does not remove them from the list of datasets
- Saving changes to a loaded dataset does not update the dataset - re-loading dataset from dataset list reverts to previous dataset spec.
- Only Save As is functioning

Browsers attempted include Chrome, Edge.
Any pointers?

**Comment by benkeen** [comment]
Hi @jfinighan, thanks for posting. Hmm, sounds like maybe there's a deeper problem going on - I tried those things: deleting a data set, saving, reloading old version - all works just fine on my end. 

Couple of questions
- Does this occur for _all_ your datasets or just one that you were testing with? Maybe creating a totally new one and see if that works or not. 
- Regardless, with the failing data set, open up Dev Tools in your browser and click on the "Networks" tab. That'll list all the requests going on when you interact with the webpage. After clicking an action that fails to work (say, delete), take a look at what you see - any errors returns from the server? Sorry for the quick instructions - just out of the country - so if this isn't enough info no worries, just let me know and I'll provide some more details instructions when I next get internet.

**Comment by jfinighan** [comment]
All good Ben. We are, among other things, seasoned software testers here and the Dev Tools are very familiar!

I will check out the network calls etc and see if I can see any glitches there.

Justin Finighan
Director
Finrea
Mob: +61 418 516 871

**Comment by jfinighan** [comment]
Hi Ben,

After making a change to a Dataset, I click save – each time I click save the following error appears in the console:
app-dfc92cd76897e2661ec8.js:81

       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'success')
    at app-dfc92cd76897e2661ec8.js:81:27200
    at Generator.next (<anonymous>)
    at i (app-dfc92cd76897e2661ec8.js:81:24714)
(anonymous) @ app-dfc92cd76897e2661ec8.js:81
i @ app-dfc92cd76897e2661ec8.js:81
Promise.then (async)
s @ app-dfc92cd76897e2661ec8.js:81
(anonymous) @ app-dfc92cd76897e2661ec8.js:81
g @ app-dfc92cd76897e2661ec8.js:81
(anonymous) @ app-dfc92cd76897e2661ec8.js:81
(anonymous) @ vendors~app-dfc92cd76897e2661ec8.js:2
onSave @ app-dfc92cd76897e2661ec8.js:255
s @ vendors~app-dfc92cd76897e2661ec8.js:2
p @ vendors~app-dfc92cd76897e2661ec8.js:2
(anonymous) @ vendors~app-dfc92cd76897e2661ec8.js:2
g @ vendors~app-dfc92cd76897e2661ec8.js:2
at @ vendors~app-dfc92cd76897e2661ec8.js:2
it @ vendors~app-dfc92cd76897e2661ec8.js:2
st @ vendors~app-dfc92cd76897e2661ec8.js:2
pt @ vendors~app-dfc92cd76897e2661ec8.js:2
L @ vendors~app-dfc92cd76897e2661ec8.js:2
z @ vendors~app-dfc92cd76897e2661ec8.js:2
Jt @ vendors~app-dfc92cd76897e2661ec8.js:2
Kt @ vendors~app-dfc92cd76897e2661ec8.js:2
t.unstable_runWithPriority @ vendors~app-dfc92cd76897e2661ec8.js:2
Vi @ vendors~app-dfc92cd76897e2661ec8.js:2
I @ vendors~app-dfc92cd76897e2661ec8.js:2
Qt @ vendors~app-dfc92cd76897e2661ec8.js:2


Also getting lots of these:
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
account:1
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
account:1
etc

Delete action, either in the Dataset list or from the dropdown in a loaded dataset does not throw any errors, but is ineffectual.

Save As throws no errors and works correctly.

I hope this helps. Let me know if a .har is useful, or a video.

Cheers
Justin

Justin Finighan
Director
Finrea
Mob: +61 418 516 871

**Comment by benkeen** [comment]
Thanks for the details! I'll look at this in the next week or so when I'm back. Something's clearly up.

**Comment by jfinighan** [comment]
Thanks Ben. The work around – using Save as – is getting me through. Enjoy your trip!

Justin Finighan
Director
Finrea
Mob: +61 418 516 871

**Comment by benkeen** [comment]
Hey @jfinighan, curious one! There _was_ another issue spotted with an Export Type (C#) failing to work. I ended up just rebooting the server and doing a fresh deploy & that issue magically resolved itself. Possibly it was a symptom of a failed deploy or docker failing to upload the latest files to the container. Would you mind taking another look? If it's still a problem, email me at ben.keen@gmail.com your login email address and I'll see if I can reproduce it with your data sets. Conceivably it's data-related.

**Comment by benkeen** [comment]
I'm going to close this now, as per my last comment. But please do ping me if you're still having problems.
