### ISSUE TITLE
generator for c# does not work

### ISSUE THREAD

**Issue by seas243** [benkeen/generatedata#830]
Hi,

the generator for c# does not work. Preview is okay, but on generating it runs endless.

**Comment by benkeen** [comment]
Thanks @seas243, I'll take a look at this for the next release.

**Comment by benkeen** [comment]
Veeerrrryy puzzling. I don't see any problem here at all, but I _am_ seeing problems on the live site. Possibly a deployment error, I'm going to redeploy the code.

**Comment by benkeen** [comment]
Hey @seas243, would you mind trying again? I restarted the server and redeployed. The problem I saw with the C# Export Type not even showing preview data l has been fixed and is generating fine for both small + large volumes of data. Curious to know if it's also fixed for you.
