### ISSUE TITLE
Missing property 'ru' in localeFileMap.ts

### ISSUE THREAD

**Issue by alex-scn** [benkeen/generatedata#831]
While installing i got the error :

../client/_localeFileMap.ts:3:14 - error TS2741: **Property 'ru'** is missing in type '{ ar: string; de: string; en: string; es: string; fr: string; hi: string; ja: string; nl: string; pt: string; ta: string; zh: string; }' but required in type 'GDLocaleMap'.

3 export const localeFileMap: GDLocaleMap = {
               ~~~~~~~~~~~~~


Found 1 error in ../client/_localeFileMap.ts:3

**Comment by benkeen** [comment]
Sorry about that, I'll try to take a look tonight.
