### ISSUE TITLE
When using SQL and update, the primary_key ( id )  value goes back to 1 after it hits 50

### ISSUE THREAD

**Issue by 0deuce0** [benkeen/generatedata#834]
Example:

UPDATE `myTable` SET `empid` = "WWN-163687" WHERE `id` = 48;
UPDATE `myTable` SET `empid` = "GQV-634639" WHERE `id` = 49;
UPDATE `myTable` SET `empid` = "DDL-735258" WHERE `id` = 50;
UPDATE `myTable` SET `empid` = "LDI-646246" WHERE `id` = 1;
UPDATE `myTable` SET `empid` = "KKU-473544" WHERE `id` = 2;
UPDATE `myTable` SET `empid` = "YKU-379575" WHERE `id` = 3;

**Comment by benkeen** [comment]
Gah, you're absolutely right, apologies. I'll patch it in the next release.
