### ISSUE TITLE
The tool breaks when changing the Date Format

### ISSUE THREAD

**Issue by nikita-makarov** [benkeen/generatedata#835]
If I change the date format to something like MM/DD/YYYY, opening up a saved dataset, it says "No Data, add some rows"
<img width="640" alt="image" src="https://github.com/benkeen/generatedata/assets/17715831/03141da9-c6e9-4643-a985-05e6cc388718">

After refreshing the page, it just keeps on spinning into the perpetuity. I tried with Edge, Chrome, and Firefox.
<img width="1013" alt="image" src="https://github.com/benkeen/generatedata/assets/17715831/6254cb17-dc98-4b2d-b045-b4e2f442311a">

**Comment by nikita-makarov** [comment]
It looks like changing the data format to MM/dd/yyyy did the trick

**Comment by benkeen** [comment]
Hi @nikita-makarov - thanks for locating the cause, and sorry for the bug! I'll look into a fix tonight.

**Comment by nikita-makarov** [comment]
thank you @benkeen !!! The tool is great, really useful for my use case (and way cheaper than everything else out there)

**Comment by benkeen** [comment]
Thanks! I just patched it in the repo, but probably won't deploy it for a few days - I have some other stuff I'd like to get in the next release.
