### ISSUE TITLE
How to create a column that the value is an array

### ISSUE THREAD

**Issue by dxu73** [benkeen/generatedata#90]
Does this tool support generating JSON document in which a field value is an array.

For example, how to generate a document like the following. Note: The 'Hobbies' field value is an array:

{ 'Name' : 'Jane', 'Address' : '123 Main Street', 'Hobbies' : [ 'Ski', 'Read', 'Jogging']}

**Comment by gbordelgit** [comment]
hey,
would be good to support array items ['1','2','3']as a sql column for postgresql ..
