### ISSUE TITLE
Is there any way to generate a set of data and in which the rows are correlated to each other

### ISSUE THREAD

**Issue by dxu73** [benkeen/generatedata#91]
Is there any way to generate a set ( let's say 100 rows) of data, and give some constraint of the distribution of values in a field.

For example: Generate 100 rows of data, each row have a field of 'Score'.
And I want 30% of my 'Score' within range of <65; 30% of 'Score' value with range 65 ~80; and 40% to be in >90.

Also, another possible constraint:   generate 100 rows of data, in which 25% of the data's 'Lastname' field is 'Smith'.

**Comment by benkeen** [comment]
I'm closing out all old issues. This is largely addressed in v4, now in production. Certain Data Types like Countries, Regions, Cities, Postal Codes and more can all be linked to one another.
